server:
  port: 8000

spring:
  application:
    name: user-service

  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/demo-project
        # registration:
        #   keycloak:
        #     provider: baeldung-keycloak
        #     authorization-grant-type: authorization_code
        #     client-id: services-client
        #     client-secret: o9598LSQb6mQcv501cECrq9m8m9fEYZx
        #     scope: openid
